import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

function App() {
  const [parts, setParts] = useState([]);
  const [formData, setFormData] = useState({
    name: "",
    price: "",
    quantity: "",
  });
  const [isAdmin, setIsAdmin] = useState(false);
  const [adminPassword, setAdminPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [editingPartId, setEditingPartId] = useState(null);
  const [quoteItems, setQuoteItems] = useState([]);
  const [quotes, setQuotes] = useState([]);
  const [customerName, setCustomerName] = useState("");
  

  const fetchParts = () => {
    fetch("http://localhost:5001/api/parts")
      .then((res) => res.json())
      .then((data) => setParts(data))
      .catch((err) => console.error(err));
  };

  const addToQuote = (part) => {
    setQuoteItems((prevItems) => {
      const existing = prevItems.find((item) => item._id === part._id);

      if (existing) {
        return prevItems.map((item) =>
          item._id === part._id
            ? { ...item, quoteQuantity: item.quoteQuantity + 1 }
            : item
        );
      }

      return [...prevItems, { ...part, quoteQuantity: 1 }];
    });
  };

  const total = quoteItems.reduce(
    (sum, item) => sum + item.price * item.quoteQuantity,
    0
  );

  const removeFromQuote = (id) => {
    setQuoteItems((prevItems) => prevItems.filter((item) => item._id !== id));
  };

  const increaseQuantity = (id) => {
    setQuoteItems(items =>
      items.map(item =>
        item._id === id
          ? { ...item, quoteQuantity: item.quoteQuantity + 1 }
          : item
      )
    );
  };

  const decreaseQuantity = (id) => {
    setQuoteItems(items =>
      items.map(item =>
        item._id === id && item.quoteQuantity > 1
          ? { ...item, quoteQuantity: item.quoteQuantity - 1 }
          : item
      )
    );
  };

  const generatePDF = () => {
    if (quoteItems.length === 0) {
      setErrorMessage("No items in quote.");
      return;
    }

    const doc = new jsPDF();

    const quoteNumber = `QT-${Date.now()}`;
    const today = new Date().toLocaleDateString();

    const companyName = "Auto Parts Quote System";
    const companyAddress = "Brooklyn, NY";
    const companyContact = "Phone: (555) 123-4567 | Email: sales@example.com";

    const displayCustomerName = customerName || "Walk-in Customer";

    const subtotal = quoteItems.reduce(
      (sum, item) => sum + item.price * item.quoteQuantity,
      0
    );

    const taxRate = 0.0875;
    const taxAmount = subtotal * taxRate;
    const grandTotal = subtotal + taxAmount;

    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(companyName, 14, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(companyAddress, 14, 27);
    doc.text(companyContact, 14, 33);

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Quotation", 150, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Quote No: ${quoteNumber}`, 150, 28);
    doc.text(`Date: ${today}`, 150, 34);

    doc.setFont("helvetica", "bold");
    doc.text("Bill To:", 14, 48);
    doc.setFont("helvetica", "normal");
    doc.text(displayCustomerName, 14, 54);

    const tableBody = quoteItems.map((item, index) => [
      index + 1,
      item.name,
      `$${item.price.toFixed(2)}`,
      item.quoteQuantity,
      `$${(item.price * item.quoteQuantity).toFixed(2)}`
    ]);

    autoTable(doc, {
      startY: 62,
      head: [["#", "Part Name", "Unit Price", "Qty", "Line Total"]],
      body: tableBody,
      theme: "grid",
      styles: {
        fontSize: 10,
        cellPadding: 3
      },
      headStyles: {
        fillColor: [41, 128, 185]
      },
      columnStyles: {
        0: { halign: "center", cellWidth: 12 },
        2: { halign: "right" },
        3: { halign: "center", cellWidth: 18 },
        4: { halign: "right" }
      }
    });

    const finalY = doc.lastAutoTable.finalY || 80;

    doc.setFont("helvetica", "normal");
    doc.text(`Subtotal: $${subtotal.toFixed(2)}`, 140, finalY + 12);
    doc.text(`Tax: $${taxAmount.toFixed(2)}`, 140, finalY + 20);

    doc.setFont("helvetica", "bold");
    doc.text(`Total: $${grandTotal.toFixed(2)}`, 140, finalY + 30);

    doc.setFont("helvetica", "bold");
    doc.text("Notes:", 14, finalY + 20);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Thank you for your business. Prices are subject to change without notice.",
      14,
      finalY + 28
    );

    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(9);
    doc.text("Generated by Auto Parts Quote System", 14, pageHeight - 10);

    doc.save(`${quoteNumber}.pdf`);
  };

  useEffect(() => {
    fetchParts();
    fetchQuotes();
  }, []);

  useEffect(() => {
    const savedAdminStatus = localStorage.getItem("isAdmin");
    const savedAdminPassword = localStorage.getItem("adminPassword");

    if (savedAdminStatus === "true" && savedAdminPassword) {
      setIsAdmin(true);
      setAdminPassword(savedAdminPassword);
    }
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;

    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleAdminLogin = (e) => {
    e.preventDefault();

    if (adminPassword === "admin123") {
      setIsAdmin(true);
      setErrorMessage("");
      localStorage.setItem("isAdmin", "true");
      localStorage.setItem("adminPassword", adminPassword);
    } else {
      setErrorMessage("Incorrect admin password");
    }
  };

  const handleAdminLogout = () => {
    setIsAdmin(false);
    setAdminPassword("");
    setEditingPartId(null);
    setFormData({
      name: "",
      price: "",
      quantity: "",
    });
    localStorage.removeItem("isAdmin");
    localStorage.removeItem("adminPassword");
  };

  const handleEdit = (part) => {
    setEditingPartId(part._id);
    setFormData({
      name: part.name,
      price: part.price,
      quantity: part.quantity,
    });
    setErrorMessage("");
  };

  const handleDelete = (id) => {
    fetch(`http://localhost:5001/api/parts/${id}`, {
      method: "DELETE",
      headers: {
        "x-admin-password": adminPassword,
      },
    })
      .then((res) => {
        if (!res.ok) {
          throw new Error("Failed to delete part");
        }
        return res.json();
      })
      .then(() => {
        fetchParts();
      })
      .catch((err) => {
        console.error(err);
        setErrorMessage("Unable to delete part.");
      });
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    const url = editingPartId
      ? `http://localhost:5001/api/parts/${editingPartId}`
      : "http://localhost:5001/api/parts";

    const method = editingPartId ? "PUT" : "POST";

    fetch(url, {
      method,
      headers: {
        "Content-Type": "application/json",
        "x-admin-password": adminPassword,
      },
      body: JSON.stringify({
        name: formData.name,
        price: Number(formData.price),
        quantity: Number(formData.quantity),
      }),
    })
      .then((res) => {
        if (!res.ok) {
          throw new Error("Failed to save part");
        }
        return res.json();
      })
      .then(() => {
        setFormData({
          name: "",
          price: "",
          quantity: "",
        });
        setEditingPartId(null);
        setErrorMessage("");
        fetchParts();
      })
      .catch((err) => {
        console.error(err);
        setErrorMessage("Unable to save part. Admin authorization failed.");
      });
  };

  const handleCancelEdit = () => {
    setEditingPartId(null);
    setFormData({
      name: "",
      price: "",
      quantity: "",
    });
    setErrorMessage("");
  };

  //获取历史报价
  const fetchQuotes = () => {
    fetch("http://localhost:5001/api/quotes")
      .then((res) => res.json())
      .then((data) => setQuotes(data))
      .catch((err) => console.error(err));
  };

  //保存当前报价
  const saveQuote = () => {
  if (quoteItems.length === 0) {
    setErrorMessage("No items in quote.");
    return;
  }

  fetch("http://localhost:5001/api/quotes", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      items: quoteItems.map((item) => ({
        partId: item._id,
        name: item.name,
        price: item.price,
        quoteQuantity: item.quoteQuantity,
      })),
      total,
    }),
  })
    .then((res) => {
      if (!res.ok) {
        throw new Error("Failed to save quote");
      }
      return res.json();
    })
    .then(() => {
      setErrorMessage("");
      fetchQuotes();
    })
    .catch((err) => {
      console.error(err);
      setErrorMessage("Unable to save quote.");
    });
};

  return (
    <div className="min-h-screen bg-slate-100 py-8 px-4">
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <h1 className="text-3xl font-bold">Parts Management</h1>

          {isAdmin ? (
            <button
              onClick={handleAdminLogout}
              className="bg-gray-700 hover:bg-gray-800 text-white px-4 py-2 rounded-lg"
            >
              Exit Admin Mode
            </button>
          ) : (
            <span className="text-sm text-gray-500">View Mode</span>
          )}
        </div>

        {!isAdmin && (
          <div className="bg-white shadow-md rounded-xl p-6 mb-8">
            <h2 className="text-xl font-semibold mb-4">Admin Access</h2>

            <form
              onSubmit={handleAdminLogin}
              className="flex flex-col md:flex-row gap-4"
            >
              <input
                type="password"
                placeholder="Enter admin password"
                value={adminPassword}
                onChange={(e) => setAdminPassword(e.target.value)}
                className="border rounded-lg px-4 py-2 flex-1"
              />

              <button
                type="submit"
                className="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2"
              >
                Enter Admin Mode
              </button>
            </form>

            {errorMessage && (
              <p className="text-red-500 mt-3 text-sm">{errorMessage}</p>
            )}
          </div>
        )}

        {isAdmin && (
          <div className="bg-white shadow-md rounded-xl p-6 mb-8">
            <h2 className="text-xl font-semibold mb-4">
              {editingPartId ? "Edit Part" : "Add New Part"}
            </h2>

            <form
              onSubmit={handleSubmit}
              className="grid grid-cols-1 md:grid-cols-4 gap-4"
            >
              <input
                type="text"
                name="name"
                placeholder="Part Name"
                value={formData.name}
                onChange={handleChange}
                className="border rounded-lg px-4 py-2"
                required
              />

              <input
                type="number"
                name="price"
                placeholder="Price"
                value={formData.price}
                onChange={handleChange}
                className="border rounded-lg px-4 py-2"
                required
              />

              <input
                type="number"
                name="quantity"
                placeholder="Quantity"
                value={formData.quantity}
                onChange={handleChange}
                className="border rounded-lg px-4 py-2"
                required
              />

              <button
                type="submit"
                className="bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-4 py-2"
              >
                {editingPartId ? "Update Part" : "Add Part"}
              </button>
            </form>

            {editingPartId && (
              <button
                onClick={handleCancelEdit}
                className="mt-4 bg-gray-200 hover:bg-gray-300 text-gray-800 px-4 py-2 rounded-lg"
              >
                Cancel Edit
              </button>
            )}

            {errorMessage && (
              <p className="text-red-500 mt-3 text-sm">{errorMessage}</p>
            )}
          </div>
        )}

        <div className="bg-white shadow-md rounded-xl p-6">
          <h2 className="text-xl font-semibold mb-4">Parts List</h2>

          <table className="table-auto border border-gray-300 w-full">
            <thead className="bg-gray-100">
              <tr>
                <th className="border px-4 py-2 text-left">Name</th>
                <th className="border px-4 py-2 text-left">Price</th>
                <th className="border px-4 py-2 text-left">Quantity</th>
                <th className="border px-4 py-2 text-left">Add</th>
                {isAdmin && (
                  <th className="border px-4 py-2 text-left">Actions</th>
                )}
              </tr>
            </thead>

            <tbody>
              {parts.map((part) => (
                <tr key={part._id}>
                  <td className="border px-4 py-2">{part.name}</td>
                  <td className="border px-4 py-2">${part.price}</td>
                  <td className="border px-4 py-2">{part.quantity}</td>
                  <td className="border px-4 py-2">
                    <button
                      onClick={() => addToQuote(part)}
                      className="bg-green-600 hover:bg-green-700 text-white px-3 py-1 rounded-lg"
                    >
                      Add
                    </button>
                  </td>

                  {isAdmin && (
                    <td className="border px-4 py-2">
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleEdit(part)}
                          className="bg-yellow-500 hover:bg-yellow-600 text-white px-3 py-1 rounded-lg"
                        >
                          Edit
                        </button>

                        <button
                          onClick={() => handleDelete(part._id)}
                          className="bg-red-600 hover:bg-red-700 text-white px-3 py-1 rounded-lg"
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="mt-10 bg-white p-6 rounded-xl shadow">
          <h2 className="text-xl font-semibold mb-4">Quote Builder</h2>
          <input
            type="text"
            placeholder="Customer Name"
            value={customerName}
            onChange={(e) => setCustomerName(e.target.value)}
            className="border rounded-lg px-4 py-2 mb-4 w-full"
          />
          {quoteItems.length === 0 && <p>No items selected</p>}

          {quoteItems.map(item => (
            <div key={item._id} className="flex justify-between items-center mb-2">
              
              <span>{item.name}</span>

              <div className="flex items-center gap-2">
                <button
                  onClick={() => decreaseQuantity(item._id)}
                  className="bg-gray-300 px-2 rounded"
                >
                  -
                </button>

                <span>{item.quoteQuantity}</span>

                <button
                  onClick={() => increaseQuantity(item._id)}
                  className="bg-gray-300 px-2 rounded"
                >
                  +
                </button>
              </div>

              <span>${item.price * item.quoteQuantity}</span>

              <button
                onClick={() => removeFromQuote(item._id)}
                className="bg-red-500 text-white px-2 py-1 rounded"
              >
                Remove
              </button>
            </div>
          ))}

          <div className="mt-4 flex gap-4">
            <button
              onClick={generatePDF}
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg"
            >
              Generate PDF
            </button>

            <button
              onClick={saveQuote}
              className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg"
            >
              Save Quote
            </button>
          </div>
        </div>
        <div className="mt-4 font-bold">
          Total: ${total}
        </div>
        <div>
          <button
            onClick={() => setQuoteItems([])}
            className="mt-4 bg-gray-500 text-white px-4 py-2 rounded"
          >
            Clear Quote
          </button>
        </div>
        <div className="mt-10 bg-white p-6 rounded-xl shadow">
          <h2 className="text-xl font-semibold mb-4">Quote History</h2>

          {quotes.length === 0 && <p>No saved quotes yet.</p>}

          {quotes.map((quote) => (
            <div key={quote._id} className="border rounded-lg p-4 mb-4">
              
              <p className="text-sm text-gray-500 mb-2">
                {new Date(quote.createdAt).toLocaleString()}
              </p>

              {quote.items.map((item, index) => (
                <div key={index} className="text-sm">
                  {item.name} x {item.quoteQuantity} - $
                  {item.price * item.quoteQuantity}
                </div>
              ))}
              <p className="font-semibold">
                Total: ${quote.total}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
    
  );
}

export default App;