import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

const COMPANY = {
  name: "Auto Parts Quote System",
  address: "Brooklyn, NY",
  contact: "Phone: (555) 123-4567 | Email: sales@example.com",
};

const TAX_RATE = 0.0875;

export function generateQuotePDF({ customerName, quoteItems, vehicle }) {
  if (quoteItems.length === 0) {
    throw new Error("No items in quote.");
  }

  const doc = new jsPDF();
  const quoteNumber = `QT-${Date.now()}`;
  const today = new Date().toLocaleDateString();
  const displayCustomerName = customerName || "Walk-in Customer";
  const vehicleText = [vehicle.year, vehicle.make, vehicle.model]
    .filter(Boolean)
    .join(" ");

  const subtotal = quoteItems.reduce(
    (sum, item) => sum + Number(item.price) * item.quoteQuantity,
    0
  );
  const taxAmount = subtotal * TAX_RATE;
  const grandTotal = subtotal + taxAmount;

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(COMPANY.name, 14, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(COMPANY.address, 14, 27);
  doc.text(COMPANY.contact, 14, 33);

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Quotation", 150, 20);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Quote No: ${quoteNumber}`, 150, 28);
  doc.text(`Date: ${today}`, 150, 34);

  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 14, 48);
  doc.setFont("helvetica", "normal");
  doc.text(displayCustomerName, 14, 54);

  doc.setFont("helvetica", "bold");
  doc.text("Vehicle:", 14, 62);
  doc.setFont("helvetica", "normal");
  doc.text(vehicleText || "Not specified", 14, 68);

  const tableBody = quoteItems.map((item, index) => [
    index + 1,
    item.name,
    `$${Number(item.price).toFixed(2)}`,
    item.quoteQuantity,
    `$${(Number(item.price) * item.quoteQuantity).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 76,
    head: [["#", "Part Name", "Unit Price", "Qty", "Line Total"]],
    body: tableBody,
    theme: "grid",
    styles: {
      fontSize: 10,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [41, 128, 185],
    },
    columnStyles: {
      0: { halign: "center", cellWidth: 12 },
      2: { halign: "right" },
      3: { halign: "center", cellWidth: 18 },
      4: { halign: "right" },
    },
  });

  const finalY = doc.lastAutoTable.finalY || 80;

  doc.setFont("helvetica", "normal");
  doc.text(`Subtotal: $${subtotal.toFixed(2)}`, 140, finalY + 12);
  doc.text(`Tax: $${taxAmount.toFixed(2)}`, 140, finalY + 20);

  doc.setFont("helvetica", "bold");
  doc.text(`Total: $${grandTotal.toFixed(2)}`, 140, finalY + 30);

  doc.setFont("helvetica", "bold");
  doc.text("Notes:", 14, finalY + 20);
  doc.setFont("helvetica", "normal");
  doc.text(
    "Thank you for your business. Prices are subject to change without notice.",
    14,
    finalY + 28
  );

  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(9);
  doc.text(`Generated by ${COMPANY.name}`, 14, pageHeight - 10);

  doc.save(`${quoteNumber}.pdf`);
  return quoteNumber;
}
